### PR TITLE
Remove development-only pom.xml file

### PR DESCRIPTION
**Pull request by semperos**

### CODE REVIEW

**Review by tobias — APPROVED** [review]

**Comment by virgofx** [comment]
Hurray!

**Comment by favila** [comment]
The real versions are still here? https://github.com/useshortcut/spymemcached/blob/master%2Bpatches-on-couchbase-spymemcached/ivy/libraries.properties

**Comment by semperos** [comment]
@favila That is what Ivy relies on, yes. I also can't get Ivy to resolve the dependencies when I run `ant jar`, but given our discussion about how spymemcached is consumed by backend, we're basically electing to ignore this repository and cover the security surface area for it in useshortcut/backend.

**Comment by favila** [comment]
Also I'm pretty sure the pom in the release artifact doesn't mention any of these: https://github.com/useshortcut/spymemcached/blob/master%2Bpatches-on-couchbase-spymemcached/spymemcached-2.12.3.sc5.pom

**Pull request merged**
