### PR TITLE
Reapply patches on top of aws-elasticache fork

### PR DESCRIPTION
**Pull request by favila**
This is all the patches we applied over the couchbase repo re-applied over the awslabs fork tag v1.1.3 instead.

Adds a bit to the top of the README explaining what this is.

### CODE REVIEW

**Review by virgofx — APPROVED** [review]
Appreciate the thorough documentation. I don't have any feedback on the technical/Java changes but looks fine at a high level.

**Review by pgroudas — APPROVED** [review]
Thanks again!

**Review by tobias — APPROVED** [review]

**Review by pgroudas — APPROVED** [review]
LGTM.

Thanks for doing this!

We will need to update this as part of the datomic upgrade:
http://github.com/useshortcut/backend/blob/main/tools/codedeploy-helper/resources/shared/set_default_java_opts.bash#L122-L132

**Comment by favila** [comment]
https://github.com/useshortcut/backend/pull/9543

**Pull request merged**
